language: ruby
rvm:
- 2.2.2
env:
  global:
    - BLOBBY_S3_TEST_BUCKET=blobby-s3-test-ap-southeast-1
    - AWS_ACCESS_KEY_ID=AKIAI7QKS6WHW6T7JAPA
    - secure: "uK7zdCn+zAQQALMD2RGJyif/+hKz6lKpBLL1hi9P7h1UzyUkArQ97zpjEOEpUWi26nU8bpyVtVNtuGh7nUKm2YdHlOw6E3uSfCXDUwgAMGgiFsQdrXx4lecIHlh8sfSa3lROmbjgYrbNarbKKSJeyY/guwf+NnssKutomXfDiLjHPAhRpUdXqfGA/k+ivehgvdSVDYDcoV2zpPYjYTtZEGkTlvENv9YZqjDY0NUad1XaKJOULcGKj8Wk9RmpUCl2Hrc39VOjmB2blTC/Il9edP+F24dJRmHR8a/tG9kPia5jIqU/UFE0PJco3XgS8rITtjREixUXScwyJDTgeguitbLiw5W8f3qI+12BC4OxQNCAxPDfZr+sxXPZdTZ8qDsC5a/4i58rp+YGSWcFMpL4DQ3MGTufh1Ny5xCFBIu8tUOjD1PuTXAM+De//jPjaYERNTbBldBZKCi0DHwo37agcg69kCYy4A5Q2H/8i52mBYLKsi47OasJTKlZ0caol3wQUsYNY5OGrfHWFz+t5nORwgbF+x9D6TtedphWtpNy62aZFYMmMxud0dX+LfZKm3xi+AlSdZZ5fw/Un5jFKAe1MqNsinkh7+OVyreoZD8MqTUvK3YDOZXHLb5S0FRcqtkN/Dj2PVWzDnhO1hTHK/dhF5EF+axCgcpYNjdgJfhjx28="
